services:
  backend:
    build:
      context: ./back-end
      args:
        COMPOSE_BAKE: "true"
    container_name: backend
    ports:
      - "3333:3333"
      - "5555:5555"
    volumes:
      - ./back-end:/var/www
    networks:
      - reservai  
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgres://p_user:p_password@db:5432/reservai_db?schema=public
      JWT_SECRET: wjeyi3geygf6egewfgbf4rjr03jrr8h4r8jr8h6F2i2eeubevfehfbfhbe
      JWT_REFRESH_SECRET: tV7!aF1pY#t9Kr3b&z2uJz8wQ6dHkW5M1L4cVoR%lBGGTJU6453HJ7Xy9oNzGzTDjHq!FqWpL2vZ%R7uXh6jI8Tk9d5sN4pQcU1aY0zSgBqR@t9eXlV#KiW3oYpJ!
    restart: unless-stopped

  frontend:
    build:
      context: ./front-end
    container_name: frontend
    volumes:
      - ./front-end:/app
    ports:
      - "5173:5173"
    networks:
      - reservai
    depends_on:
      - backend

  db:
    image: postgres:latest
    container_name: db
    environment:
      POSTGRES_PASSWORD: p_password
      POSTGRES_USER: p_user
      POSTGRES_DB: reservai_db
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - reservai
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U p_user -d reservai_db"]
      interval: 5s
      retries: 5
    restart: unless-stopped

networks:
  reservai:
    driver: bridge

volumes:
  postgres-data:
