FROM node:22-alpine

WORKDIR /var/www

RUN corepack enable && \ 
    corepack prepare pnpm@latest --activate

COPY package*.json pnpm-lock.yaml ./

COPY . .

RUN pnpm install --frozen-lockfile

RUN pnpx prisma generate

EXPOSE 3333

CMD ["sh", "-c", "pnpx prisma migrate dev && pnpm run dev"]
