FROM node:18-alpine

WORKDIR /var/www

COPY package*.json yarn.lock ./

COPY . .

RUN yarn install 

EXPOSE 3333

RUN yarn prisma generate

ENTRYPOINT ["sh", "-c", "yarn prisma migrate dev --name $(date +%Y%m%d%H%M%S) && yarn dev"]


