version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile

    volumes:
      - ..:/app

    ports:
      - "3333:3333"

    depends_on: [db]

    environment:
      DATABASE_URL: postgres://p_user:p_password@db:5432/reservai_db

    command: sleep infinity

    networks:
      - reservai

  db:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
      # - ../initdb.d:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_PASSWORD: p_password
      POSTGRES_USER: p_user
      POSTGRES_DB: reservai_db

    networks:
      - reservai

networks:
  reservai:
    driver: bridge

volumes:
  postgres-data:
